Feature/db challenge2
yongdai/quelcode-db pull request #2
Opened 2020-07-05 16:38 UTC by yongdai

DB課題2についてテーブル定義書とDDL文を提出します。レビューをお願い致します。

2020-07-06 03:28 UTC, piasoratech requested changes
以下について確認と修正をお願いします。
- 要件を満たせていない項目があります。
- 要件に書かれていない制約などは付与する必要はありません。

2020-07-06 04:46 UTC, piasoratech requested changes
まだ課題要件を満たせていないので確認と修正をお願いします。
また、SQLの文法についてもミスがあるのでチェッカーを使用したうえで提出をするようお願いします。

2020-07-06 06:51 UTC, piasoratech requested changes
命名の部分でまだあまり良くない部分が多いので一度Sliteに記載されているTipsのQiita記事を参考にして修正をお願いします。

2020-07-06 06:51 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +CREATE TABLE User (
データベース関連で命名に大文字を使うのは一般的ではないです。
また、テーブル名は複数形にしましょう。

2020-07-06 06:51 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +    edit_date DATETIME NOT NULL
この命名もあまり良いものとは言えません。
Tips記載のQiita記事を参考にしてください

2020-07-06 08:41 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-07-06 08:41 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +    tel_office VARCHAR(20),
ここは電話番号の-を含めた最大桁数が入れば良いです。
国内の番号に限ります。

2020-07-06 09:59 UTC, piasoratech requested changes
- テーブル定義書のテーブル名が修正されていないものがあるので、修正をして下さい。
- usersテーブルの内容がDDLと異なる部分があります。
- chatroomsテーブルの内容がDDLと異なる部分があります。
- DDLでINTEGER型の部分が定義書だとINT型になっているので、どちらかに統一してください。INT型を使うほうが一般的です。

2020-07-06 09:59 UTC, piasoratech commented on db/db-challenge2/chatwork.sql
> +    member_user_id VARCHAR(255) NOT NULL REFERENCES users(user_id),
外部キーなので型を合わせましょう

2020-07-07 03:28 UTC, fjtawork commented
大丈夫そうですね、LGTM！

2020-07-07 04:21 UTC, merged